version: '3.9'

services:
  #MongoDb database
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #Api server
  app:
    build: .
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo_db:27017
      environment: development
    depends_on:
      - mongo_db
    ports:
      - 8000:8000
    volumes:
      - .:/app

volumes:
  mongo_db: {}
