version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo_db:27017
      environment: development
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mongo_db
    volumes:
      - .:/app

volumes:
  mongo_db: {}
